-- data sync uses id columns to work with data link to avoid race conditions
-- data sync can paste id values itself, but 'generated always as identity' blocks it

ALTER TABLE crm.generic_flags
    ADD COLUMN pestroutes_data_link_alias VARCHAR(50) DEFAULT NULL,
    ALTER COLUMN id SET GENERATED BY DEFAULT;

CREATE UNIQUE INDEX crm_generic_flags_data_link_alias_unique ON crm.generic_flags (pestroutes_data_link_alias);