CREATE TABLE notifications.incoming_mms_messages
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    twilio_message_id        VARCHAR(64) NOT NULL,
    twilio_media_id          VARCHAR(64) NOT NULL,
    aws_region               VARCHAR(32) NOT NULL DEFAULT '',
    aws_bucket               VARCHAR(64) NOT NULL DEFAULT '',
    aws_file_path            VARCHAR(128) NOT NULL DEFAULT '',
    temporary_url            VARCHAR(255) NULL,
    temporary_url_expiration TIMESTAMP(6) WITH TIME ZONE,
    created_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at               TIMESTAMP(6) WITH TIME ZONE,
    PRIMARY KEY (id)
);
