CREATE TABLE notifications.sms_messages (
    id int4 GENERATED BY DEFAULT AS IDENTITY,
    sid varchar NULL,
    reference_id int4 NULL,
    reference_type varchar NULL,
    sender_id int4 NULL,
    sender_type varchar NULL,
    sms_datetime TIMESTAMPTZ(6),
    message text NULL,
    "from" varchar NULL,
    "to" varchar NULL,
    status varchar NULL,
    meta jsonb NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp(6),
    updated_at timestamptz(6) NOT NULL DEFAULT current_timestamp(6),
    deleted_at timestamptz(6),
    CONSTRAINT pk_sms_messages_id PRIMARY KEY (id)
);
COMMENT ON COLUMN notifications.sms_messages.sid IS 'Service message id';

CREATE TABLE notifications.sms_messages_media (
    id int4 GENERATED BY DEFAULT AS IDENTITY,
    sms_message_id int4 NOT NULL,
    "path" varchar NULL,
    meta jsonb NULL,
    created_at timestamptz(6) NOT NULL DEFAULT current_timestamp(6),
    updated_at timestamptz(6) NOT NULL DEFAULT current_timestamp(6),
    deleted_at timestamptz(6),
    CONSTRAINT pk_sms_messages_media_id PRIMARY KEY (id),
    CONSTRAINT fk_sms_messages_media_sms_message_id_sms_messages_id
        FOREIGN KEY(sms_message_id)
            REFERENCES notifications.sms_messages(id)
            ON DELETE SET NULL
);
