CREATE TABLE `payments` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `appointment_id` INT UNSIGNED NULL DEFAULT NULL,
    `ticket_id` INT UNSIGNED NULL DEFAULT NULL,
    `amount` DOUBLE(8,2) NOT NULL,
	`success` TINYINT(1) NOT NULL DEFAULT '0',
	`request_origin` VARCHAR(255) NULL DEFAULT NULL,
	`service_response` TEXT NULL DEFAULT NULL,
	`created_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
	`updated_at` TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
	PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB;
