CREATE TABLE `credit_card_setup_links` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `customer_id` bigint unsigned NOT NULL,
  `gateway_id` bigint unsigned NOT NULL,
  `callback_url` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL COMMENT 'Customer billing name',
  `address1` varchar(255) DEFAULT NULL COMMENT 'First line of customer billing address',
  `address2` varchar(255) DEFAULT NULL COMMENT 'Second line of customer billing address',
  `city` varchar(64) DEFAULT NULL,
  `province` varchar(2) DEFAULT NULL,
  `postal_code` varchar(10) DEFAULT NULL,
  `email` varchar(255) DEFAULT NULL,
  `phone` varchar(16) DEFAULT NULL,
  `gateway_request` text,
  `gateway_response` text,
  `ext_reference_id` varchar(255) DEFAULT NULL COMMENT 'Gateway response ID (transaction setup ID)',
  `generated_urls` json DEFAULT NULL,
  `created_by` int unsigned DEFAULT NULL,
  `updated_by` int unsigned DEFAULT NULL,
  `created_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `credit_card_setup_links_gateway_id_foreign` (`gateway_id`),
  CONSTRAINT `credit_card_setup_links_gateway_id_foreign` FOREIGN KEY (`gateway_id`) REFERENCES `gateways` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
