<?php

declare(strict_types=1);

namespace Tests\Stubs;

use Aptive\PestRoutesSDK\Collection;
use Aptive\PestRoutesSDK\Resources\Tickets\Ticket;

class TicketResponses
{
    /**
     * @return Collection
     */
    public static function getEmptyTicketCollection(): Collection
    {
        return new Collection(items: [], total: 0);
    }

    /**
     * @param int|null $quantity
     * @param int|null $totalQuantity
     *
     * @return Collection
     */
    public static function getTicketCollection(int|null $quantity = null, int|null $totalQuantity = null): Collection
    {
        $tickets = [
            1 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '32770',
                    'customerID' => '8196',
                    'billToAccountID' => '8196',
                    'officeID' => '1',
                    'dateCreated' => '2016-08-09 00:00:00',
                    'invoiceDate' => '2016-08-09 00:00:00',
                    'dateUpdated' => '0000-00-00 00:00:00',
                    'active' => '1',
                    'subTotal' => '109.00',
                    'taxAmount' => '0.00',
                    'total' => '109.00',
                    'serviceCharge' => '109.00',
                    'serviceTaxable' => '0',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '16387',
                    'balance' => '12.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '21',
                    'invoiceNumber' => '32770',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [],
                ]
            ),
            2 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '32803',
                    'customerID' => '8229',
                    'billToAccountID' => '8229',
                    'officeID' => '1',
                    'dateCreated' => '2016-11-01 00:00:00',
                    'invoiceDate' => '2016-11-01 00:00:00',
                    'dateUpdated' => '0000-00-00 00:00:00',
                    'active' => '1',
                    'subTotal' => '105.00',
                    'taxAmount' => '0.00',
                    'total' => '105.00',
                    'serviceCharge' => '105.00',
                    'serviceTaxable' => '0',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '16420',
                    'balance' => '1.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '21',
                    'invoiceNumber' => '32803',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [],
                ]
            ),
            3 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '2995205',
                    'customerID' => '769659',
                    'billToAccountID' => '769659',
                    'officeID' => '1',
                    'dateCreated' => '2017-06-05 12:55:31',
                    'invoiceDate' => '2017-06-05 00:00:00',
                    'dateUpdated' => '2017-06-05 12:55:31',
                    'active' => '1',
                    'subTotal' => '49.00',
                    'taxAmount' => '0.00',
                    'total' => '49.00',
                    'serviceCharge' => '229.00',
                    'serviceTaxable' => '1',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '2088338',
                    'balance' => '0.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '2',
                    'invoiceNumber' => '2995205',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [
                        (object)[
                            'itemID' => '75223',
                            'ticketID' => '2995205',
                            'amount' => '-180.00',
                            'quantity' => '1',
                            'productID' => '0',
                            'description' => 'Initial Discount',
                            'taxable' => '1',
                            'creditTo' => '8362',
                            'unitID' => null,
                            'category' => null,
                            'code' => null,
                            'glNumber' => '',
                        ],
                    ],
                ]
            ),
            4 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '2995767',
                    'customerID' => '11098',
                    'billToAccountID' => '11098',
                    'officeID' => '1',
                    'dateCreated' => '2017-06-05 13:55:05',
                    'invoiceDate' => '2017-06-05 00:00:00',
                    'dateUpdated' => '2017-06-05 13:55:05',
                    'active' => '1',
                    'subTotal' => '109.00',
                    'taxAmount' => '0.00',
                    'total' => '109.00',
                    'serviceCharge' => '109.00',
                    'serviceTaxable' => '1',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '2087184',
                    'balance' => '0.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '21',
                    'invoiceNumber' => '2995767',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [],
                ]
            ),
            5 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '3416973',
                    'customerID' => '879697',
                    'billToAccountID' => '879697',
                    'officeID' => '1',
                    'dateCreated' => '2017-08-01 14:41:10',
                    'invoiceDate' => '2017-08-01 00:00:00',
                    'dateUpdated' => '2017-08-01 14:41:10',
                    'active' => '1',
                    'subTotal' => '0.00',
                    'taxAmount' => '0.00',
                    'total' => '0.00',
                    'serviceCharge' => '229.00',
                    'serviceTaxable' => '1',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '2517521',
                    'balance' => '0.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '2',
                    'invoiceNumber' => '3416973',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [
                        (object)[
                            'itemID' => '231050',
                            'ticketID' => '3416973',
                            'amount' => '-229.00',
                            'quantity' => '1',
                            'productID' => '0',
                            'description' => 'Initial Discount',
                            'taxable' => '1',
                            'creditTo' => '8362',
                            'unitID' => null,
                            'category' => null,
                            'code' => null,
                            'glNumber' => '',
                        ],
                    ],
                ]
            ),
            6 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '3416985',
                    'customerID' => '828346',
                    'billToAccountID' => '828346',
                    'officeID' => '1',
                    'dateCreated' => '2017-08-01 14:42:36',
                    'invoiceDate' => '2017-08-01 00:00:00',
                    'dateUpdated' => '2017-08-01 14:42:36',
                    'active' => '1',
                    'subTotal' => '89.00',
                    'taxAmount' => '0.00',
                    'total' => '89.00',
                    'serviceCharge' => '89.00',
                    'serviceTaxable' => '1',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '2502094',
                    'balance' => '0.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '21',
                    'invoiceNumber' => '3416985',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [],
                ]
            ),
            7 => Ticket::fromApiObject(
                (object)[
                    'ticketID' => '3579791',
                    'customerID' => '870609',
                    'billToAccountID' => '870609',
                    'officeID' => '1',
                    'dateCreated' => '2017-08-27 02:30:03',
                    'invoiceDate' => '2017-08-27 00:00:00',
                    'dateUpdated' => '2017-11-17 06:41:51',
                    'active' => '1',
                    'subTotal' => '0.98',
                    'taxAmount' => '0.00',
                    'total' => '0.98',
                    'serviceCharge' => '0.98',
                    'serviceTaxable' => '1',
                    'productionValue' => '-1.00',
                    'taxRate' => '0.000000',
                    'appointmentID' => '0',
                    'balance' => '0.00',
                    'subscriptionID' => '0',
                    'autoGenerated' => '0',
                    'autoGeneratedType' => 'NA',
                    'renewalID' => '0',
                    'serviceID' => '584',
                    'invoiceNumber' => '3579791',
                    'templateType' => 'NA',
                    'glNumber' => '',
                    'items' => [],
                ]
            ),
        ];

        if (is_null($quantity) || is_null($totalQuantity)) {
            return new Collection(items: $tickets, total: count($tickets));
        }

        return new Collection(
            items: array_fill(start_index: 0, count: $quantity, value: $tickets[array_rand($tickets)]),
            total: $totalQuantity
        );
    }

    public static function getTicketsArray(): array
    {
        $tickets = [];
        $tickets[] = (object)[
            'ticketID' => '3579791',
            'customerID' => '870609',
            'billToAccountID' => '870609',
            'officeID' => '1',
            'dateCreated' => '2017-08-27 02:30:03',
            'invoiceDate' => '2017-08-27 00:00:00',
            'dateUpdated' => '2017-11-17 06:41:51',
            'active' => '1',
            'subTotal' => '0.98',
            'taxAmount' => '0.00',
            'total' => '0.98',
            'serviceCharge' => '0.98',
            'serviceTaxable' => '1',
            'productionValue' => '-1.00',
            'taxRate' => '0.000000',
            'appointmentID' => '0',
            'balance' => '0.00',
            'subscriptionID' => '0',
            'autoGenerated' => '0',
            'autoGeneratedType' => 'NA',
            'renewalID' => '0',
            'serviceID' => '584',
            'invoiceNumber' => '3579791',
            'templateType' => 'NA',
            'glNumber' => '',
            'items' => [],
        ];

        return $tickets;
    }

    /**
     * @return Ticket
     */
    public static function getSingleTicket(): Ticket
    {
        return Ticket::fromApiObject(
            apiObject: (object)[
                'ticketID' => '32770',
                'customerID' => '8196',
                'billToAccountID' => '8196',
                'officeID' => '1',
                'dateCreated' => '2016-08-09 00:00:00',
                'invoiceDate' => '2016-08-09 00:00:00',
                'dateUpdated' => '0000-00-00 00:00:00',
                'active' => '1',
                'subTotal' => '109.00',
                'taxAmount' => '0.00',
                'total' => '109.00',
                'serviceCharge' => '109.00',
                'serviceTaxable' => '0',
                'productionValue' => '-1.00',
                'taxRate' => '0.000000',
                'appointmentID' => '16387',
                'balance' => '12.00',
                'subscriptionID' => '0',
                'autoGenerated' => '0',
                'autoGeneratedType' => 'NA',
                'renewalID' => '0',
                'serviceID' => '21',
                'invoiceNumber' => '32770',
                'templateType' => 'NA',
                'glNumber' => '',
                'items' => [],
            ]
        );
    }

    /**
     * @return Ticket
     */
    public static function getSingleTicketWithPaidBalance(): Ticket
    {
        return Ticket::fromApiObject(
            (object)[
                'ticketID' => '3579791',
                'customerID' => '870609',
                'billToAccountID' => '870609',
                'officeID' => '1',
                'dateCreated' => '2017-08-27 02:30:03',
                'invoiceDate' => '2017-08-27 00:00:00',
                'dateUpdated' => '2017-11-17 06:41:51',
                'active' => '1',
                'subTotal' => '0.98',
                'taxAmount' => '0.00',
                'total' => '0.98',
                'serviceCharge' => '0.98',
                'serviceTaxable' => '1',
                'productionValue' => '-1.00',
                'taxRate' => '0.000000',
                'appointmentID' => '0',
                'balance' => '0.00',
                'subscriptionID' => '0',
                'autoGenerated' => '0',
                'autoGeneratedType' => 'NA',
                'renewalID' => '0',
                'serviceID' => '584',
                'invoiceNumber' => '3579791',
                'templateType' => 'NA',
                'glNumber' => '',
                'items' => [],
            ]
        );
    }

    /**
     * @return Ticket
     */
    public static function getSingleTicketWithFutureInvoiceDate(): Ticket
    {
        return Ticket::fromApiObject(
            apiObject: (object)[
                'ticketID' => '3579791',
                'customerID' => '870609',
                'billToAccountID' => '870609',
                'officeID' => '1',
                'dateCreated' => '2017-08-27 02:30:03',
                'invoiceDate' => now()->addDay()->format(format: 'Y-m-d H:i:s'),
                'dateUpdated' => '2017-11-17 06:41:51',
                'active' => '1',
                'subTotal' => '0.98',
                'taxAmount' => '0.00',
                'total' => '0.98',
                'serviceCharge' => '0.98',
                'serviceTaxable' => '1',
                'productionValue' => '-1.00',
                'taxRate' => '0.000000',
                'appointmentID' => '0',
                'balance' => '12.34',
                'subscriptionID' => '0',
                'autoGenerated' => '0',
                'autoGeneratedType' => 'NA',
                'renewalID' => '0',
                'serviceID' => '584',
                'invoiceNumber' => '3579791',
                'templateType' => 'NA',
                'glNumber' => '',
                'items' => [],
            ]
        );
    }

    /**
     * @return Ticket
     */
    public static function getSingleTicketWithTodayDate(): Ticket
    {
        return Ticket::fromApiObject(
            apiObject: (object)[
                'ticketID' => '3579791',
                'customerID' => '870609',
                'billToAccountID' => '870609',
                'officeID' => '1',
                'dateCreated' => '2017-08-27 02:30:03',
                'invoiceDate' => now()->format(format: 'Y-m-d H:i:s'),
                'dateUpdated' => '2017-11-17 06:41:51',
                'active' => '1',
                'subTotal' => '0.98',
                'taxAmount' => '0.00',
                'total' => '0.98',
                'serviceCharge' => '0.98',
                'serviceTaxable' => '1',
                'productionValue' => '-1.00',
                'taxRate' => '0.000000',
                'appointmentID' => '0',
                'balance' => '12.34',
                'subscriptionID' => '0',
                'autoGenerated' => '0',
                'autoGeneratedType' => 'NA',
                'renewalID' => '0',
                'serviceID' => '584',
                'invoiceNumber' => '3579791',
                'templateType' => 'NA',
                'glNumber' => '',
                'items' => [],
            ]
        );
    }
}
